package:
  name: rattler-build-test
  version: 0.2.0

source:
  path: ..

build:
  number: 1
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip >=24.2
    - setuptools >=46.1.0
    - setuptools_scm >=5

  run:
    - python >=3.10
    - pandas >=1.4,<1.5
